spring:
  application:
    name: consumer-server
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    url: jdbc:mysql://localhost:3307/ShoppingDB
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: default-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      max-poll-records: 20


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
